### ISSUE TITLE
 Throws RuntimeError when executed

### ISSUE THREAD

**Issue by jrsam** [VPanjeta/ModiScript#1]
All the sample examples in /examples folder, throws `RuntimeError: generator raised StopIteration `when tried to execute.
Here is the call trace
`Traceback (most recent call last):
  File "/Users/sjaganatha/ModiScript/modiscript/MODI", line 50, in <module>
    main()
  File "/Users/sjaganatha/ModiScript/modiscript/MODI", line 46, in main
    execute(filename)
  File "/Users/sjaganatha/ModiScript/modiscript/MODI", line 28, in execute
    ast_module = compile_file(filename)
  File "/Users/sjaganatha/ModiScript/modiscript/MODI", line 15, in compile_file
    lex_out = Lexer(filename).analyze()
  File "/Users/sjaganatha/ModiScript/modiscript/lexer.py", line 75, in analyze
    lexemes = list(lexer)`

**Comment by VPanjeta** [comment]
Hi @jrsam 
Could you please give details about the OS and python version you're using?
ModiScript hasn't been ported to [PEP 479](https://www.python.org/dev/peps/pep-0479/) and the error you're receiving is probably because you're using Python 3.7.0
I suggest you create an environment with python3 version 3.6 or below and try to run it.

**Comment by jrsam** [comment]
@VPanjeta  My environment is Mac OS X El Capitan with Python 2.7.15

**Comment by VPanjeta** [comment]
Python2 version should not have any affect on the project as it is completely written in python3.
So can you type `python3 -V` in your terminal and post the result?

**Comment by jrsam** [comment]
The result is `Python 3.7.0`

**Comment by VPanjeta** [comment]
Yeah so as I mentioned, your python3 binary should be 3.6 or lower.
You can try creating an environment with python 3.6 using anaconda and activating that environment and then running it.
I'll close this issue for now as python 3.7 is still not supported

**Comment by VPanjeta** [comment]
Another solution could be that you can change the last line in modiscript/lexer.py from `raise StopIteration` to `return` (This isn't an elegant solution but gets the code running in python 3.7 as StopIteration now gives RuntimeError)

**Comment by jrsam** [comment]
Thanks. Removing `raise StopIteration` with Python 3.7 fixed the issue.

**Comment by bhawesh96** [comment]
I initially thought that this issue talked about the reality of the current Govt.
 _reads issue title again_
