### ISSUE TITLE
Feature to take audio/voice input

### ISSUE THREAD

**Issue by bhawesh96** [VPanjeta/ModiScript#26]
Some Mitra might want to simply input a recording of _His_ speech or actually speak out his/her _(mitra's)_ mann ki baat xD

Adding pyaudio and some NLP with the existing lexing and parsing should get this working!

Acche din aa gaye

**Comment by VPanjeta** [comment]
Hi @bhawesh96 

Thanks for the suggestion but ASR for Hindi might be a tough task to solve. Certainly there are pre-trained models out there but fine-tuning them to the scope of this project might still require some time. It's not something that we plan on doing for now as it might require a significant amount of time to get speech recognition on Hindi working that's fine-tuned for this project.

Closing this thread as we don't plan to add for now. Although we would be happy to accept any PR in this regard.
