### ISSUE TITLE
Undefined name: 'filename' on lines 12 and 16

### ISSUE THREAD

**Issue by cclauss** [VPanjeta/ModiScript#27]
https://github.com/VPanjeta/ModiScript/blob/master/modiscript/api.py#L12-16

**Comment by VPanjeta** [comment]
Not an issue in the main compiler but inside the API execution for Web App.
@DakshMiglani Seems like an issue with the web API. If you want to address it, you can fix it otherwise you can close this as this seems like an issue raised by an automated script.

**Comment by cclauss** [comment]
The issue was not raised by an automated script.
`NameError` will be raised if this function is called.
