### ISSUE TITLE
Why is it in Hindi?

### ISSUE THREAD

**Issue by ashikvs** [VPanjeta/ModiScript#35]
Coding in Modi script requires knowledge of Hindi which is an issue

**Comment by abhyantrika** [comment]
I do understand that we might be excluding non Hindi speakers in this project. But the idea of this project is completely intertwined with Mr Modi's speeches and idiosyncrasies, which are in Hindi. Again, we do stand strongly against the idea of Hindi imposition in India and support the case for strong vernacular linguistic foundations coupled with English as the link language. 
So, the usage of Hindi language is just to go with the theme of Mr Modi and not to exclude speakers from other parts of the nation.
