### ISSUE TITLE
Consider submitting to ESO

### ISSUE THREAD

**Issue by illandan** [VPanjeta/ModiScript#42]
I think this language would qualify under the category of [JokeLang](https://esolangs.org/wiki/Category:Joke_languages) on [esolangs.org](https://esolangs.org/). 

I'm not associated with esolangs.org in any way, although I do occasionally browse around that wiki for some sense of hilarity. Consider putting your work up there? 

:+1:

**Comment by VPanjeta** [comment]
@illandan 
Thanks for the suggestion. We have considered it before but since no one is maintaining the repository we parked the idea.
Closing this thread as it is not an issue.
